server:
  port: 8183
spring:
  application:
    name: RATING-SERVICE
  autoconfigure:
    exclude: 'org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration '
  data:
    mongodb:
      database: microservices
      uri: mongodb://localhost:27017

okta:
  oauth2:
    issuer: https://dev-48568461.okta.com/oauth2/default
    audience: api://default


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
